### ISSUE TITLE
get request headers from rpc.Server

### ISSUE THREAD

**Issue by efrazier** [pocesar/node-jsonrpc2#18]
I couldn't find a correct way to do this. In server.js I can put in a global var on the listen method, but I don't understand enough yet about how node/classes work to do it properly.  I can access global.reqHeaders from an exposed method. I know this is terrible. Is there a way to get at the request that already exists that I am just missing?  

56       listen: function (port, host) {
 57         var
 58           self = this,
 59           server = http.createServer();
 60
 61         server.on('request', function onRequest(req, res) {
+62           global.reqHeaders = req.headers;
 63           self.handleHttp(req, res);
 64         });
 65
 66         if (port) {
 67           server.listen(port, host);
 68           Endpoint.trace('***', 'Server listening on http://' +
 69             (host || '127.0.0.1') + ':' + port + '/');
 70         }
 71
 72         if (this.opts.websocket === true) {
 73           server.on('upgrade', function onUpgrade(req, socket, body) {
 74             if (WebSocket.isWebSocket(req)) {
 75               if (self._checkAuth(req, socket)) {
 76                 self.handleWebsocket(req, socket, body);
 77               }
 78             }
 79           });
 80         }
 81
 82         return server;
 83       },

**Comment by pocesar** [comment]
why would you need to do this? JSON-RPC is a protocol that abstracts the need to mess with HTTP headers and consistency, it just work. if you need to check the headers, you should be using either express, connect or hapi for that. this module is aimed for the RPC only, and you shouldn't be messing with the module source code as well.

**Comment by efrazier** [comment]
What a strange and arrogant response. Like maybe I want to know about cookies and other things about the request env? I figured from looking at the code that this would be the reaction to my question. I guess I can always learn what I need to somewhere else and fork.
