### ISSUE TITLE
Setting Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by dbillingham** [pocesar/node-jsonrpc2#22]
I get this issue in chrome when trying to set the Access-Control-Allow-Headers:
"Request header field x-requested-with is not allowed by Access-Control-Allow-Headers."

This is because on line 126 of server.js you are overriding what is passed in with some defaults:

          headers = {
            'Content-Length': 0,
            'Access-Control-Allow-Headers': 'Accept, X-Requested-With, Authorization, Content-Type'
          };
          headers = extend(self.opts.headers, headers);

If the user specifies a Access-Control-Allow-Headers should that not overwrite this default, (so the extend be the other way around)?:

          headers = extend(headers, self.opts.headers);

**Comment by pocesar** [comment]
good catch, will apply a fix and release it today

**Comment by pocesar** [comment]
test the branch https://github.com/pocesar/node-jsonrpc2/tree/issue-%2322 to see if it's working now

**Comment by dbillingham** [comment]
Yeah looks good, and works for me.

**Comment by pocesar** [comment]
released as 1.0.2, thanks!
